# Generated by Django 6.0.8 on 2026-08-29 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='due_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
